services:
  inventory-service:
    build: ./inventory-service
    container_name: inventory-service
    ports:
      - '8081:8081'
    expose:
      - '8081'
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8081/actuator/health" ]
      interval: 10s
      retries: 4
  order-service:
    build: ./orderservice
    container_name: order-service
    ports:
      - '8082:8082'
    expose:
      - '8082'
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8082/actuator/health"]
      interval: 10s
      retries: 4
    depends_on:
      inventory-service:
        condition: service_healthy
  inventory-client:
    build: ./inventory-client
    container_name: inventory-client
    ports:
      - '82:80'
    expose:
      - '82'
